import {
  BROKEN_CLOUDS,
  CLEAR_SKY,
  DRIZZLE,
  DRIZZLE_RAIN,
  DUST,
  FEW_CLOUDS,
  FOG,
  FREEZING_RAIN,
  HAZE,
  HEAVY_INTENSITY_DRIZZLE,
  HEAVY_INTENSITY_DRIZZLE_RAIN,
  HEAVY_INTENSITY_RAIN,
  HEAVY_INTENSITY_SHOWER_RAIN,
  HEAVY_SHOWER_RAIN_AND_DRIZZLE,
  HEAVY_SHOWER_SNOW,
  HEAVY_SNOW,
  HEAVY_THUNDERSTORM,
  LIGHT_INTENSITY_DRIZZLE,
  LIGHT_INTENSITY_DRIZZLE_RAIN,
  LIGHT_INTENSITY_SHOWER_RAIN,
  LIGHT_RAIN,
  LIGHT_RAIN_AND_SNOW,
  LIGHT_SHOWER_SLEET,
  LIGHT_SHOWER_SNOW,
  LIGHT_SNOW,
  LIGHT_THUNDERSTORM,
  MIST,
  MODERATE_RAIN,
  OVERCAST_CLOUDS,
  RAGGED_SHOWER_RAIN,
  RAGGED_THUNDERSTORM,
  RAIN_AND_SNOW,
  SAND,
  SAND_DUST_WHIRLS,
  SCATTERED_CLOUDS,
  SHOWER_DRIZZLE,
  SHOWER_RAIN,
  SHOWER_RAIN_AND_DRIZZLE,
  SHOWER_SLEET,
  SHOWER_SNOW,
  SLEET,
  SMOKE,
  SNOW,
  SQUALLS,
  THUNDERSTORM,
  THUNDERSTORM_WITH_DRIZZLE,
  THUNDERSTORM_WITH_HEAVY_DRIZZLE,
  THUNDERSTORM_WITH_HEAVY_RAIN,
  THUNDERSTORM_WITH_LIGHT_DRIZZLE,
  THUNDERSTORM_WITH_LIGHT_RAIN,
  THUNDERSTORM_WITH_RAIN,
  TORNADO,
  VERY_HEAVY_RAIN,
  VOLCANIC_ASH,
} from "./conditionDescriptions";

const THUNDERSTORMMAP = new Map();
THUNDERSTORMMAP.set(200, THUNDERSTORM_WITH_LIGHT_RAIN);
THUNDERSTORMMAP.set(201, THUNDERSTORM_WITH_RAIN);
THUNDERSTORMMAP.set(202, THUNDERSTORM_WITH_HEAVY_RAIN);
THUNDERSTORMMAP.set(210, LIGHT_THUNDERSTORM);
THUNDERSTORMMAP.set(211, THUNDERSTORM);
THUNDERSTORMMAP.set(212, HEAVY_THUNDERSTORM);
THUNDERSTORMMAP.set(221, RAGGED_THUNDERSTORM);
THUNDERSTORMMAP.set(230, THUNDERSTORM_WITH_LIGHT_DRIZZLE);
THUNDERSTORMMAP.set(231, THUNDERSTORM_WITH_DRIZZLE);
THUNDERSTORMMAP.set(232, THUNDERSTORM_WITH_HEAVY_DRIZZLE);

const DRIZZLEMAP = new Map();
DRIZZLEMAP.set(300, LIGHT_INTENSITY_DRIZZLE);
DRIZZLEMAP.set(301, DRIZZLE);
DRIZZLEMAP.set(302, HEAVY_INTENSITY_DRIZZLE);
DRIZZLEMAP.set(310, LIGHT_INTENSITY_DRIZZLE_RAIN);
DRIZZLEMAP.set(311, DRIZZLE_RAIN);
DRIZZLEMAP.set(312, HEAVY_INTENSITY_DRIZZLE_RAIN);
DRIZZLEMAP.set(313, SHOWER_RAIN_AND_DRIZZLE);
DRIZZLEMAP.set(314, HEAVY_SHOWER_RAIN_AND_DRIZZLE);
DRIZZLEMAP.set(321, SHOWER_DRIZZLE);

const RAINMAP = new Map();
RAINMAP.set(500, LIGHT_RAIN);
RAINMAP.set(501, MODERATE_RAIN);
RAINMAP.set(502, HEAVY_INTENSITY_RAIN);
RAINMAP.set(504, VERY_HEAVY_RAIN);
RAINMAP.set(511, FREEZING_RAIN);
RAINMAP.set(520, LIGHT_INTENSITY_SHOWER_RAIN);
RAINMAP.set(521, SHOWER_RAIN);
RAINMAP.set(522, HEAVY_INTENSITY_SHOWER_RAIN);
RAINMAP.set(531, RAGGED_SHOWER_RAIN);

const SNOWMAP = new Map();
SNOWMAP.set(600, LIGHT_SNOW);
SNOWMAP.set(601, SNOW);
SNOWMAP.set(602, HEAVY_SNOW);
SNOWMAP.set(611, SLEET);
SNOWMAP.set(612, LIGHT_SHOWER_SLEET);
SNOWMAP.set(613, SHOWER_SLEET);
SNOWMAP.set(615, LIGHT_RAIN_AND_SNOW);
SNOWMAP.set(616, RAIN_AND_SNOW);
SNOWMAP.set(620, LIGHT_SHOWER_SNOW);
SNOWMAP.set(621, SHOWER_SNOW);
SNOWMAP.set(622, HEAVY_SHOWER_SNOW);

const ATMOSPHEREMAP = new Map();
ATMOSPHEREMAP.set(701, MIST);
ATMOSPHEREMAP.set(711, SMOKE);
ATMOSPHEREMAP.set(721, HAZE);
ATMOSPHEREMAP.set(731, SAND_DUST_WHIRLS);
ATMOSPHEREMAP.set(741, FOG);
ATMOSPHEREMAP.set(751, SAND);
ATMOSPHEREMAP.set(761, DUST);
ATMOSPHEREMAP.set(762, VOLCANIC_ASH);
ATMOSPHEREMAP.set(771, SQUALLS);
ATMOSPHEREMAP.set(781, TORNADO);

const CLEARSKYMAP = new Map();
CLEARSKYMAP.set(800, CLEAR_SKY);

const CLOUDSMAP = new Map();
CLOUDSMAP.set(801, FEW_CLOUDS);
CLOUDSMAP.set(802, SCATTERED_CLOUDS);
CLOUDSMAP.set(803, BROKEN_CLOUDS);
CLOUDSMAP.set(804, OVERCAST_CLOUDS);

export const WEATHER_CONDITION_MAPS = {
  THUNDERSTORMMAP,
  DRIZZLEMAP,
  RAINMAP,
  SNOWMAP,
  ATMOSPHEREMAP,
  CLEARSKYMAP,
  CLOUDSMAP,
};
