import {TEMP_SPECTRUM_COLD, TEMP_SPECTRUM_ZERO, TEMP_SPECTRUM_CHILLY, TEMP_SPECTRUM_WARMLY, TEMP_SPECTRUM_HOT} from "../constants/tempSpectrumValues"

export type tempSpectrumStrings = typeof TEMP_SPECTRUM_COLD | typeof TEMP_SPECTRUM_ZERO | typeof TEMP_SPECTRUM_CHILLY | typeof TEMP_SPECTRUM_WARMLY | typeof TEMP_SPECTRUM_HOT
